// not a big deal, just some snapshot tests for the displaySuggestions function
// to make sure it doesn't break when I refactor stuff
// should be good until Alfred changes it's API

import assert from "node:assert";
import displaySuggestions from "./pj.mjs";
import clipboard from "./testdata.json" assert { type: "json" };

const { equal } = assert;
const data = JSON.stringify(clipboard);

function test(filter, expectedOutput) {
    const output = displaySuggestions(data, filter);
    equal(output, expectedOutput);
}

test("", `{"items":[{"title":"a field","subtitle":"\\"value1\\"","autocomplete":"[\\"a field\\"]","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"[\\"a field\\"]","icon":{"path":"./icons/copy.png"}}}},{"title":"another_field","subtitle":"Object (keys: 2)","autocomplete":"another_field","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field","icon":{"path":"./icons/copy.png"}}}},{"title":"some-other-field","subtitle":"Array (length: 2)","autocomplete":"[\\"some-other-field\\"]","valid":false,"icon":{"path":"./icons/array.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"[\\"some-other-field\\"]","icon":{"path":"./icons/copy.png"}}}},{"title":"empty_array","subtitle":"Array (length: 0)","autocomplete":"empty_array","valid":false,"icon":{"path":"./icons/array.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"empty_array","icon":{"path":"./icons/copy.png"}}}},{"title":"empty_object","subtitle":"Object (keys: 0)","autocomplete":"empty_object","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"empty_object","icon":{"path":"./icons/copy.png"}}}}]}`);;
test("b", `{"items":[{"title":"No such property","valid":false,"icon":{"path":"./icons/error.png"}}]}`);
test("a", `{"items":[{"title":"a field","subtitle":"\\"value1\\"","autocomplete":"[\\"a field\\"]","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"[\\"a field\\"]","icon":{"path":"./icons/copy.png"}}}},{"title":"another_field","subtitle":"Object (keys: 2)","autocomplete":"another_field","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field","icon":{"path":"./icons/copy.png"}}}}]}`);
test('["a field"]', `{"items":[{"title":"\\"value1\\"","subtitle":"string - Copy to clipboard","arg":"\\"value1\\"","autocomplete":"[\\"a field\\"]","valid":true,"icon":{"path":"./icons/copy.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"[\\"a field\\"]","icon":{"path":"./icons/copy.png"}}}}]}`);
test("an", `{"items":[{"title":"another_field","subtitle":"Object (keys: 2)","autocomplete":"another_field","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field", `{"items":[{"title":"subfield1","subtitle":"\\"value2\\"","autocomplete":"another_field.subfield1","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield1","icon":{"path":"./icons/copy.png"}}}},{"title":"subfield2","subtitle":"Object (keys: 5)","autocomplete":"another_field.subfield2","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field.", `{"items":[{"title":"subfield1","subtitle":"\\"value2\\"","autocomplete":"another_field.subfield1","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield1","icon":{"path":"./icons/copy.png"}}}},{"title":"subfield2","subtitle":"Object (keys: 5)","autocomplete":"another_field.subfield2","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field..", `{"items":[{"title":"No such property","valid":false,"icon":{"path":"./icons/error.png"}}]}`);
test('["another_field"]', `{"items":[{"title":"subfield1","subtitle":"\\"value2\\"","autocomplete":"[\\"another_field\\"].subfield1","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield1","icon":{"path":"./icons/copy.png"}}}},{"title":"subfield2","subtitle":"Object (keys: 5)","autocomplete":"[\\"another_field\\"].subfield2","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2","icon":{"path":"./icons/copy.png"}}}}]}`);
test("['another_field']", `{"items":[{"title":"subfield1","subtitle":"\\"value2\\"","autocomplete":"['another_field'].subfield1","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield1","icon":{"path":"./icons/copy.png"}}}},{"title":"subfield2","subtitle":"Object (keys: 5)","autocomplete":"['another_field'].subfield2","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2","icon":{"path":"./icons/copy.png"}}}}]}`);
test('["some-other-field"]', `{"items":[{"title":"0","subtitle":"\\"value4\\"","autocomplete":"[\\"some-other-field\\"][0]","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"[\\"some-other-field\\"][0]","icon":{"path":"./icons/copy.png"}}}},{"title":"1","subtitle":"\\"value5\\"","autocomplete":"[\\"some-other-field\\"][1]","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"[\\"some-other-field\\"][1]","icon":{"path":"./icons/copy.png"}}}}]}`);
test('["some-other-field"][0]', `{"items":[{"title":"\\"value4\\"","subtitle":"string - Copy to clipboard","arg":"\\"value4\\"","autocomplete":"[\\"some-other-field\\"][0]","valid":true,"icon":{"path":"./icons/copy.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"[\\"some-other-field\\"][0]","icon":{"path":"./icons/copy.png"}}}}]}`);
test('["some-other-field"][2]', `{"items":[{"title":"No such property","valid":false,"icon":{"path":"./icons/error.png"}}]}`);
test("emp", `{"items":[{"title":"empty_array","subtitle":"Array (length: 0)","autocomplete":"empty_array","valid":false,"icon":{"path":"./icons/array.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"empty_array","icon":{"path":"./icons/copy.png"}}}},{"title":"empty_object","subtitle":"Object (keys: 0)","autocomplete":"empty_object","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"empty_object","icon":{"path":"./icons/copy.png"}}}}]}`);
test("empty_array", `{"items":[{"title":"Empty","subtitle":"Array (length: 0)","valid":false,"icon":{"path":"./icons/array.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"","icon":{"path":"./icons/copy.png"}}}}]}`);
test("empty_object", `{"items":[{"title":"Empty","subtitle":"Object (keys: 0)","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field.su", `{"items":[{"title":"subfield1","subtitle":"\\"value2\\"","autocomplete":"another_field.subfield1","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield1","icon":{"path":"./icons/copy.png"}}}},{"title":"subfield2","subtitle":"Object (keys: 5)","autocomplete":"another_field.subfield2","valid":false,"icon":{"path":"./icons/object.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field.subfield1", `{"items":[{"title":"\\"value2\\"","subtitle":"string - Copy to clipboard","arg":"\\"value2\\"","autocomplete":"another_field.subfield1","valid":true,"icon":{"path":"./icons/copy.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield1","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field.subfield2", `{"items":[{"title":"apple","subtitle":"\\"value3\\"","autocomplete":"another_field.subfield2.apple","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.apple","icon":{"path":"./icons/copy.png"}}}},{"title":"orange","subtitle":"true","autocomplete":"another_field.subfield2.orange","valid":false,"icon":{"path":"./icons/bool.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.orange","icon":{"path":"./icons/copy.png"}}}},{"title":"grape","subtitle":123,"autocomplete":"another_field.subfield2.grape","valid":false,"icon":{"path":"./icons/number.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.grape","icon":{"path":"./icons/copy.png"}}}},{"title":"peach","subtitle":123.456,"autocomplete":"another_field.subfield2.peach","valid":false,"icon":{"path":"./icons/number.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.peach","icon":{"path":"./icons/copy.png"}}}},{"title":"pinapple","subtitle":null,"autocomplete":"another_field.subfield2.pinapple","valid":false,"icon":{"path":"./icons/null.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.pinapple","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field.subfield2[[", `{"items":[{"title":"apple","subtitle":"\\"value3\\"","autocomplete":"another_field.subfield2[[.apple","valid":false,"icon":{"path":"./icons/string.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.apple","icon":{"path":"./icons/copy.png"}}}},{"title":"orange","subtitle":"true","autocomplete":"another_field.subfield2[[.orange","valid":false,"icon":{"path":"./icons/bool.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.orange","icon":{"path":"./icons/copy.png"}}}},{"title":"grape","subtitle":123,"autocomplete":"another_field.subfield2[[.grape","valid":false,"icon":{"path":"./icons/number.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.grape","icon":{"path":"./icons/copy.png"}}}},{"title":"peach","subtitle":123.456,"autocomplete":"another_field.subfield2[[.peach","valid":false,"icon":{"path":"./icons/number.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.peach","icon":{"path":"./icons/copy.png"}}}},{"title":"pinapple","subtitle":null,"autocomplete":"another_field.subfield2[[.pinapple","valid":false,"icon":{"path":"./icons/null.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.pinapple","icon":{"path":"./icons/copy.png"}}}}]}`);
test('another_field.subfield2[["p"]', `{"items":[{"title":"peach","subtitle":123.456,"autocomplete":"another_field.subfield2.peach","valid":false,"icon":{"path":"./icons/number.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.peach","icon":{"path":"./icons/copy.png"}}}},{"title":"pinapple","subtitle":null,"autocomplete":"another_field.subfield2.pinapple","valid":false,"icon":{"path":"./icons/null.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.pinapple","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field.subfield2.peach", `{"items":[{"title":123.456,"subtitle":"number - Copy to clipboard","arg":123.456,"autocomplete":"another_field.subfield2.peach","valid":true,"icon":{"path":"./icons/copy.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.peach","icon":{"path":"./icons/copy.png"}}}}]}`);
test("another_field.subfield2.pinapple", `{"items":[{"title":null,"subtitle":"null - Copy to clipboard","arg":null,"autocomplete":"another_field.subfield2.pinapple","valid":true,"icon":{"path":"./icons/copy.png"},"mods":{"cmd":{"subtitle":"Copy property path to clipboard","arg":"another_field.subfield2.pinapple","icon":{"path":"./icons/copy.png"}}}}]}`);
